compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0006
    level: discard
  - code: YN0076
    level: discard
  - code: YN0013
    level: discard

nodeLinker: pnp

pnpIgnorePatterns:
  - ./packages/ui/**

packageExtensions:
  "tamagui-loader@*":
    peerDependencies:
      "@tamagui/proxy-worm": "*"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
